// Fetches every World Cup 2026 squad from football-data.org and bakes them into a
// static module (../../js/squads.js) the app imports at runtime — no Firestore, no
// API calls in production. Squads barely change during a tournament, so this is a
// manual/occasional build, mirroring scripts/results/ in spirit.
//
// Run: FOOTBALL_DATA_TOKEN=... node build-squads.js
//
// Free tier is rate-limited (~10 req/min), so we space requests out; the full run
// over 48 teams takes ~5 min. Teams that come back with an empty squad are logged
// so we know the source didn't have them yet.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { toPt } from '../results/teams.js';

const TOKEN = process.env.FOOTBALL_DATA_TOKEN;
const BASE = 'https://api.football-data.org/v4';
const REQUEST_SPACING_MS = 6500; // stay under the free tier's ~10 req/min ceiling
const OUT = join(dirname(fileURLToPath(import.meta.url)), '../../js/squads.js');

// Map football-data.org positions to the app's PT bucket labels (see js/app.js).
const POSITION_GROUP = {
  Goalkeeper: 'GOL',
  Defence: 'DEF',
  Midfield: 'MEI',
  Offence: 'ATA',
};

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function api(path, { retries = 3 } = {}) {
  let lastErr;
  for (let attempt = 1; attempt <= retries; attempt++) {
    const res = await fetch(`${BASE}${path}`, { headers: { 'X-Auth-Token': TOKEN } });
    if (res.ok) return res.json();
    lastErr = `${res.status}: ${(await res.text()).slice(0, 200)}`;
    // 429 = rate limited: back off harder before retrying.
    const backoff = res.status === 429 ? 60_000 : 5_000 * attempt;
    if (attempt < retries) {
      console.warn(`  ${path} -> ${res.status}; retrying in ${backoff / 1000}s...`);
      await sleep(backoff);
    }
  }
  throw new Error(`${path} failed after ${retries} tries: ${lastErr}`);
}

function buildSquad(team) {
  const players = (team.squad || []).map(p => ({
    name: p.name,
    group: POSITION_GROUP[p.position] || 'ATA',
    dob: p.dateOfBirth || null,
  }));
  return {
    coach: team.coach?.name || null,
    coachNat: team.coach?.nationality || null,
    crest: team.crest || null,
    players,
  };
}

async function main() {
  if (!TOKEN) throw new Error('Missing FOOTBALL_DATA_TOKEN.');

  console.log('Fetching WC team list...');
  const { teams } = await api('/competitions/WC/teams');
  console.log(`Found ${teams.length} teams.`);

  const squads = {};
  const empty = [];
  const unmapped = [];

  for (let i = 0; i < teams.length; i++) {
    const t = teams[i];
    const pt = toPt({ name: t.name, tla: t.tla });
    if (!pt) { unmapped.push(`${t.name}/${t.tla}`); continue; }

    await sleep(REQUEST_SPACING_MS);
    const full = await api(`/teams/${t.id}`);
    const squad = buildSquad(full);
    squads[pt] = squad;
    if (!squad.players.length) empty.push(pt);
    console.log(`  [${i + 1}/${teams.length}] ${pt}: ${squad.players.length} players, coach ${squad.coach ?? '—'}`);
  }

  // Stable key order so the generated file diffs cleanly between runs.
  const ordered = Object.fromEntries(Object.keys(squads).sort().map(k => [k, squads[k]]));
  const banner = '// AUTO-GENERATED by scripts/squads/build-squads.js — do not edit by hand.\n';
  writeFileSync(OUT, `${banner}export const SQUADS = ${JSON.stringify(ordered, null, 2)};\n`);

  console.log(`\nWrote ${Object.keys(ordered).length} squads to ${OUT}`);
  if (empty.length) console.warn(`Empty squads (source had no players): ${empty.join(', ')}`);
  if (unmapped.length) console.warn(`Unmapped API teams (add to scripts/results/teams.js): ${unmapped.join(', ')}`);
}

main().catch(err => { console.error(err); process.exit(1); });
